name: Test Priority Runner
on:
  workflow_dispatch:
  push:
    branches: ['test-priority-*']

jobs:
  test:
    runs-on: tt-ubuntu-2204-n300-prio-stable
    steps:
      - run: echo "This should not run"
