name: Test Priority Runner
on:
  workflow_dispatch:
  merge_group:
  pull_request:

jobs:
  regular-job:
    runs-on: tt-ubuntu-2204-n300-viommu-stable
    steps:
      - run: echo "Regular job picked up"

  priority-job:
    runs-on: tt-ubuntu-2204-n300-viommu-prio-stable
    steps:
      - run: echo "Priority job picked up"
