name: Test priority runner
on:
  merge_group:

jobs:
  test:
    runs-on:
      group: organization/Default
      labels: tt-ubuntu-2204-small-prio-stable
    steps:
      - run: echo "merge_group trigger works"